### ISSUE TITLE
Login in issue

### ISSUE THREAD

**Issue by Heath41** [jorexdeveloper/termux-nethunter#13] opened 2024-10-15 07:38 UTC
┌────────────────────────────────────────┐
      │╻┏ ┏━┓╻  ╻   ┏┓╻┏━╸╺┳╸╻ ╻╻ ╻┏┓╻╺┳╸┏━╸┏━┓│
      │┣┻┓┣━┫┃  ┃   ┃┗┫┣╸  ┃ ┣━┫┃ ┃┃┗┫ ┃ ┣╸ ┣┳┛│
      │╹ ╹╹ ╹┗━╸╹   ╹ ╹┗━╸ ╹ ╹ ╹┗━┛╹ ╹ ╹ ┗━╸╹┗╸│
      │                 2024.3                 │            └────────────────────────────────────────┘
                     Author: Jore                           Github: https://github.com/jorexdeveloper/      
  * Checking device architecture.                         arm64-v8a is supported.                           
  * Updating system.                                      System update complete.                           
  * Checking for package dependencies.                    'tar' is installed.
    'wget' is installed.
    'proot' is installed.
    'unzip' is installed.
    Installing 'pulseaudio'.
    'pulseaudio' is installed.

  * Using '/data/data/com.termux/files/kali' as rootfs directory.

  * Select rootfs installation.
        [1] Kali NetHunter-arm64-Full
        [2] Kali NetHunter-arm64-Minimal
        [3] Kali NetHunter-arm64-Nano (default)
    Enter choice: 1
    Installing 'full' rootfs.

  * Downloading rootfs archive.
kali-nethunte 100%   2.01G  1.97MB/s    in 14m 49s
2024-10-15 08:09:53 URL:https://kali.download/nethunter-images/kali-2024.3/rootfs/kali-nethunter-rootfs-full-arm64.tar.xz [2161167124/2161167124] -> "kali-nethunter-rootfs-full-arm64.tar.xz.nhdownload" [1]
    Rootfs archive download complete.

  * Verifying the integrity of the rootfs archive.
    Rootfs archive is ok.

  * Extracting rootfs archive.
    Rootfs extracted successfully.

  * Creating Kali NetHunter launcher.
    Kali NetHunter launcher created successfully.

  * Creating the VNC launcher.
    VNC launcher was created successfully.

  * Making required configurations.
    fake proc setup success.
    android ids setup success.
    settings configurations failed. (status -0-255-0-0-0)
    environment variables setup success.

  * Making optional configurations.

y
    Available shells: bash zsh fish dash tcsh csh ksh
    Enter shell name: bash
chsh: avc.c:73: avc_context_to_sid_raw: Assertion `avc_running' failed.
proot info: vpid 1: terminated with signal 6
    Failed to set default login shell. Try again? (y/N): n

  * Change the default time zone? (y/N): n
    Delete the rootfs archive to save space? (y/N):
    Rootfs archive left.

  * Kali NetHunter installed successfully.
    Run command 'nethunter' or 'nh' to start Kali NetHunter.
    Run command 'vnc' in Kali NetHunter to start the VNC server.

  * Login Information
    Root user
        [1] Login    'root'
        [2] Password 'root'
    Normal user
        [1] Login    'kali'
        [2] Password 'kali'

  * Documentation  https://github.com/jorexdeveloper/termux-nethunter
~ $ nh
localhost login: kali
Password:
A valid context for kali could not be obtained.

Cannot make/remove an entry for the specified session
~ $

**Comment by Heath41** [comment] 2024-10-15 18:42
──(root㉿localhost)-[~]
└─# passwd kali
passwd: avc.c:73: avc_context_to_sid_raw: Assertion `avc_running' failed.
Aborted

┌──(root㉿localhost)-[~]
└─#

**Comment by Sagar72-ui** [comment] 2024-10-16 09:09
Github: https://github.com/jorexdeveloper/
  * Checking device architecture.                     arm64-v8a is supported.
  * Updating system.                                  System update complete.

  * Checking for package dependencies.                'tar' is installed.                               'wget' is installed.                              'proot' is installed.                             'unzip' is installed.
    'pulseaudio' is installed.

  * Using '/data/data/com.termux/files/kali' as rootfs directory.

  * Select rootfs installation.
        [1] Kali NetHunter-arm64-Full
        [2] Kali NetHunter-arm64-Minimal
        [3] Kali NetHunter-arm64-Nano (default)
1
    Installing 'full' rootfs.

  * Rootfs directory found.
        [1] Use directory.
        [2] Delete directory.
        [3] Leave directory and exit. (default)
    Select action: 1
    Using rootfs directory.

  * Creating Kali NetHunter launcher.
    Kali NetHunter launcher created successfully.

  * Creating the VNC launcher.
    VNC launcher was created successfully.

  * Making required configurations.
    fake proc setup success.
    android ids setup success.
    settings configurations failed. (status -0-255-0-0-0)
    environment variables setup success.

  * Making optional configurations.

  * Change the default login shell? (y/N): n

  * Change the default time zone? (y/N): n

  * Kali NetHunter installed successfully.
    Run command 'nethunter' or 'nh' to start Kali NetHunter.
    Run command 'vnc' in Kali NetHunter to start the VNC server.

  * Login Information
    Root user
        [1] Login    'root'
        [2] Password 'root'
    Normal user
        [1] Login    'kali'
        [2] Password 'kali'

  * Documentation  https://github.com/jorexdeveloper/termux-nethunter
~/termux-nethunter $ nethunter
localhost login: kali
Password:
A valid con

**Comment by Sagar72-ui** [comment] 2024-10-16 09:09
Github: https://github.com/jorexdeveloper/
  * Checking device architecture.                     arm64-v8a is supported.
  * Updating system.                                  System update complete.

  * Checking for package dependencies.                'tar' is installed.                               'wget' is installed.                              'proot' is installed.                             'unzip' is installed.
    'pulseaudio' is installed.

  * Using '/data/data/com.termux/files/kali' as rootfs directory.

  * Select rootfs installation.
        [1] Kali NetHunter-arm64-Full
        [2] Kali NetHunter-arm64-Minimal
        [3] Kali NetHunter-arm64-Nano (default)
1
    Installing 'full' rootfs.

  * Rootfs directory found.
        [1] Use directory.
        [2] Delete directory.
        [3] Leave directory and exit. (default)
    Select action: 1
    Using rootfs directory.

  * Creating Kali NetHunter launcher.
    Kali NetHunter launcher created successfully.

  * Creating the VNC launcher.
    VNC launcher was created successfully.

  * Making required configurations.
    fake proc setup success.
    android ids setup success.
    settings configurations failed. (status -0-255-0-0-0)
    environment variables setup success.

  * Making optional configurations.

  * Change the default login shell? (y/N): n

  * Change the default time zone? (y/N): n

  * Kali NetHunter installed successfully.
    Run command 'nethunter' or 'nh' to start Kali NetHunter.
    Run command 'vnc' in Kali NetHunter to start the VNC server.

  * Login Information
    Root user
        [1] Login    'root'
        [2] Password 'root'
    Normal user
        [1] Login    'kali'
        [2] Password 'kali'

  * Documentation  https://github.com/jorexdeveloper/termux-nethunter
~/termux-nethunter $ nethunter
localhost login: kali
Password:
A valid con

**Comment by jorexdeveloper** [comment] 2024-10-16 21:30
> ──(root㉿localhost)-[~] └─# passwd kali passwd: avc.c:73: avc_context_to_sid_raw: Assertion `avc_running' failed. Aborted
> 
> ┌──(root㉿localhost)-[~] └─#

This is probably caused by some bugs in the rootfs itself, but i shall provide a solution/work around

**Comment by jorexdeveloper** [comment] 2024-10-16 21:35
I have committed the updated script to simply delete all passwords hence fixing the login issue, you should now be able to login without a password, a user name will still be required

**Comment by jorexdeveloper** [comment] 2024-10-16 21:35
Feel free to reopen issue if solution fails to work

**Closed by jorexdeveloper** 2024-10-16 21:35 UTC

**Comment by Sagar72-ui** [comment] 2024-10-18 14:26
I am here to help you to install Kali NetHunter.
 ✔ First, lemme check if your device architecture is supported.                                                Great! 'arm64-v8a' is supported.
 ✔ Now lemme check if all system packages are up to date. Just a sec...
   Yup! Everything looks good. Let's proceed.
 ✔ Hold on while I check if all the required packages are installed.
   Oops, 'pulseaudio' is missing. Let me install it now...
   Done! 'pulseaudio' is now installed.
   Great! You have all the required packages! Let's get started!
 ✔ I shall now install Kali NetHunter in '/data/data/com.termux/files/kali'.
 ✔ Select your prefered installation.
       <1>   full    (Large but contains everything you need)
       <2>   minimal (Light-weight with basic packages only)
       <3> > nano    (Like minimal with a few more packages)
   Enter choice: 1
   Okay then, I shall install a full rootfs.
 ✔ Alright, it's time to download the rootfs archive. This might take a while...
kali-nethunter-rootfs-full-arm64.tar.xz.pe   6%[====>                                   r.xz.pending           82%[====================>     ]   1.66G  77.3KB/s    eta 1kali-nethunter-rootfs-full-arm64.tar.xz.pe  87%[===============================================kali-nethunter-rootfs-full-arm64.tar.xz.pe  87%[==========================kali-nethunter-rootfs-full-arm64.tar.xz.pe 100%[=====================================================================================>]   2.01G  1.64MB/s    in 61m 0s
2024-10-18 18:55:39 URL:https://kali.download/nethunter-images/kali-2024.3/rootfs/kali-nethunter-rootfs-full-arm64.tar.xz [2161167124/2161167124] -> "kali-nethunter-rootfs-full-arm64.tar.xz.pending" [1]
   Great! The rootfs download is complete.
 ✔ Give me a sec to verify the integrity of the rootfs archive...
   Yup, the rootfs archive is looks fine.
 ✔ Grab a coffee while I extract the rootfs archive. This will take a while...
   Finally, I am done extracting the rootfs archive.
 ✔ Lemme create a command to launch Kali NetHunter.
   Command created successfully.
 ✔ Lemme create a command to launch VNC in Kali NetHunter.
   Command created successfully.
 ✔ Now let me make some configurations for you.
   Oops, settings configurations failed with error code: (-0-255-0-0-0)
   Yup, that should fix some startup issues.

 ✔ Should I change the default time zone? (y/N): n
   Should I remove the downloaded the rootfs archive to save space? (y/N): n
   Alright, lemme leave the rootfs archive.
 ✔ That's it! We have successfuly installed Kali NetHunter.
   You can launch it by executing:
   'nethunter root' to login as root user.
   or
   'nethunter kali' to login as a normal user.
 ✔ I also figured you might need a short form for 'nethunter'.
   In that case, I created 'nh' that does the same thing.
 ✔ If you have further inquiries, read the documentation at:
   https://github.com/jorexdeveloper/termux-nethunter
~ $ nethunter root
Password:
Login timed out after 60 seconds.
~ $
bash: install-nethunter.shnethunter: No such file or directory
~ $
Password:

Login incorrect
localhost login: kali
Password:
A valid context for kali could not be obtained.

Cannot make/remove an entry for the specified session
~ $again error please give sulation and fixed error please sir give me sulation  immediately
My phone is not rooted this methode is work an my phone sir i request you sir
